steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://source.developers.google.com/p/pork-merchant/r/cloudrepo']

# - name: 'gcr.io/cloud-builders/git'
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     mkdir -p ~/.ssh
#     ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
#     ssh-keygen -t rsa -C "user.gitauwairimu@gmail.com"
#     git clone git@github.com:Gitauwairimu/Jenkins_Maven.git
#     cd /java-tomcat-sample

# - name: 'ubuntu'
#   args: ['echo', 'hello world']


- name: maven:3-jdk-8
  entrypoint: mvn
  args: ['package','-Dmaven.test.skip=true']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/pork-merchant/javaimage:v1', '.']
  dir: 'java-tomcat-sample'
# images:
#   - 'us-central1-docker.pkg.dev/pork-merchant/javaimage:v1'
   # Docker Push
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'us-central1-docker.pkg.dev/pork-merchant/javaimage:v1']
logsBucket: 'gs://artifacts.pork-merchant.appspot.com'
# options:
#   logging: CLOUD_LOGGING_ONLY